source 'https://github.com/CocoaPods/Specs.git'

target 'compresJSON-Pod', :exclusive => true do
  pod "compresJSON-Pod", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "compresJSON-Pod", :path => "../"

  pod 'FBSnapshotTestCase'
end
